# Arg 1: a dot file representing a CFG, generated by opt -dot-cfg
OUTPUT=${1%.*}.labels-only.dot
# remove anything but labels
sed 's/\(label="{%[[:digit:]][[:digit:]]*\).*}"];/\1}"];/' $1 > $OUTPUT
# strip ports
sed 's/\(Node0x[^:]*\):s[[:digit:]][[:digit:]]*/\1/' $OUTPUT -i

